name: dawaa24
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#Android
version: 1.0.0+1
#ios
#version: 1.0.0+2

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  internet_connection_checker: ^1.0.0+1
  injectable: ^2.4.2
  flutter_screenutil: ^5.9.1
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  intl: ^0.19.0
  google_fonts:
  google_maps_flutter: ^2.6.1
  location: ^6.0.2
  font_awesome_flutter: ^10.7.0
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.10+1
  easy_localization: ^3.0.7
  go_router: ^14.1.3
  dotted_border: ^2.1.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  image_picker: ^1.1.1
#  file_picker: ^8.0.3
#  flutter_file_dialog: ^3.0.2
  flutter_pdfview: ^1.3.2
  file_selector: ^1.0.3
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  dotted_decoration: ^2.0.0
  equatable: ^2.0.5
  timeago: ^3.6.1
  pull_to_refresh: ^2.0.0
  #  flutter_google_places: ^0.3.0
  google_api_headers: ^4.0.3
  cached_memory_image: ^1.5.0
  sqflite: ^2.3.3+1
  badges: ^3.1.2
  flutter_slidable:
    git:
      url: https://github.com/BaselSuleman/flutter_slidable
      ref: master
  steps_indicator: ^1.3.0
  geocoding: ^3.0.0
  fluttertoast: ^8.2.5
  launch_review: ^3.0.1
  package_info_plus: ^8.0.0
  local_auth: ^2.2.0
  url_launcher: ^6.2.6
  flutter_cupertino_date_picker_fork: ^1.0.7
  lottie: ^3.1.2
  cached_network_image: ^3.3.1
  qr_code_scanner: ^1.0.1
  permission_handler: ^11.3.1
  scan: ^1.6.0
  flutter_html:
  agora_chat_sdk: ^1.2.0
  google_places_flutter: ^2.0.8
  animate_icons: ^2.0.0
  readmore: ^3.0.0
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1+2
  share_plus: ^9.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.10
  flutter_gen_runner: ^5.5.0+1
  #notiice dev dependency!!!!!!!!!
  flutter_launcher_icons: "^0.9.2"
  pretty_dio_logger: ^1.3.1

  logger:
    git:
      url: https://github.com/mohamd34/logger.git
      ref: stacktrace_option # branch name


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/dawaa_icon_app.png"
  #flutter pub run flutter_launcher_icons:main


flutter_gen:
  output: lib/core/presentation/resources/
  line_length: 80 # Optional (default: 80)
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/google_maps_styles/
    - assets/animation/
    - assets/temp/